{%- if mcu == "esp32c3" -%}
[target.riscv32imac-unknown-none-elf]
{%- else -%}
[target.xtensa-{{ mcu }}-none-elf]
{%- endif %}
runner = "espflash --monitor"

[build]
{% if mcu == "esp32c3" -%}
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
]
target = "riscv32imac-unknown-none-elf"
{%- else -%}
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",
]
target = "xtensa-{{ mcu }}-none-elf"
{%- endif %}

[unstable]
build-std = ["core"]
